# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Stonewall Inn
email: KKelly99@aol.com
description: > # this means to ignore newlines until "baseurl:"
  53 Christopher Street, New York, NY
  The legendary Stonewall Inn is the birthplace of the modern Gay Rights movement.
baseurl: "/stonewall" # the subpath of your site, e.g. /blog
url: "http://hannataylor.github.io/stonewall" # the base hostname & protocol for your site
twitter_username: TheStonewallNYC
facebook_url: TheStonewallInn
instagram_username: thestonewallinn

# Build settings
markdown: kramdown

# Handling Reading
include: ['_pages']